// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(ControleContext))]
    [Migration("20240301110823_UpdateEntites")]
    partial class UpdateEntites
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("API.Entities.Record", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CctAdresse")
                        .HasColumnType("TEXT");

                    b.Property<string>("CctCodeCommune")
                        .HasColumnType("TEXT");

                    b.Property<string>("CctDenomination")
                        .HasColumnType("TEXT");

                    b.Property<string>("CctSiret")
                        .HasColumnType("TEXT");

                    b.Property<string>("CctTel")
                        .HasColumnType("TEXT");

                    b.Property<string>("CctUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeDepartement")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePostal")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeRegion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Departement")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
