// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(ControleContext))]
    [Migration("20240222194827_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("API.Entities.Coordgeo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double>("Lon")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Coordgeo");
                });

            modelBuilder.Entity("API.Entities.Fields", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CctAdresse")
                        .HasColumnType("TEXT");

                    b.Property<string>("CctCodeCommune")
                        .HasColumnType("TEXT");

                    b.Property<string>("CctDenomination")
                        .HasColumnType("TEXT");

                    b.Property<string>("CctSiret")
                        .HasColumnType("TEXT");

                    b.Property<string>("CctTel")
                        .HasColumnType("TEXT");

                    b.Property<string>("CctUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeDepartement")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePostal")
                        .HasColumnType("TEXT");

                    b.Property<long>("CodeRegion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoordgeoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Departement")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoordgeoId");

                    b.ToTable("Field");
                });

            modelBuilder.Entity("API.Entities.Fields", b =>
                {
                    b.HasOne("API.Entities.Coordgeo", "Coordgeo")
                        .WithMany()
                        .HasForeignKey("CoordgeoId");

                    b.Navigation("Coordgeo");
                });
#pragma warning restore 612, 618
        }
    }
}
