// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(ControleContext))]
    partial class ControleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("API.Entities.Fields", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CctAdresse")
                        .HasColumnType("TEXT");

                    b.Property<string>("CctCodeCommune")
                        .HasColumnType("TEXT");

                    b.Property<string>("CctDenomination")
                        .HasColumnType("TEXT");

                    b.Property<string>("CctSiret")
                        .HasColumnType("TEXT");

                    b.Property<string>("CctTel")
                        .HasColumnType("TEXT");

                    b.Property<string>("CctUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeDepartement")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePostal")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeRegion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Departement")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Field");
                });

            modelBuilder.Entity("API.Entities.Record", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FieldsId");

                    b.HasIndex("RootId");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("API.Entities.Root", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roots");
                });

            modelBuilder.Entity("API.Entities.Record", b =>
                {
                    b.HasOne("API.Entities.Fields", "Fields")
                        .WithMany()
                        .HasForeignKey("FieldsId");

                    b.HasOne("API.Entities.Root", null)
                        .WithMany("Records")
                        .HasForeignKey("RootId");

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("API.Entities.Root", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
